GET http://localhost:3000/products/3

###

POST http://localhost:3000/products
Content-Type: application/json

{
"product": "camera",
"price": 5, 
"description": "takes pictures"
}


###

PATCH http://localhost:3000/products/10
Content-Type: application/json

{
  "item": "desk"
}
